### ISSUE TITLE
Does not watch sass imported files

### ISSUE THREAD

**Issue by supercoww** [Sonaryr/eleventy-plugin-sass#10]
I have a main.scss file which imports a table.scss file:
```scss
@import './table.scss';

// some styles
```
and these are my plugin options:
```js
eleventyConfig.addPlugin(pluginSass, {
	watch: ['src/styles/main.scss'],
});
```

The plugin does not rebuild the main.scss file when I update the table.scss file. To trigger the update, I have to save main.scss file each time I make changes in table.scss. I did not add table.scss to the watch option because I don't need it in the final build.

**Comment by tgdev** [comment]
@supercoww `tables.scss` is currently a scss output file in terms of how the sass compiler sees it but it seems like you really want to use it as a partial to be included in your main.scss file.

I believe if you make tables.scss a partial (`_tables.scss`) and update your watch config to `watch: ['src/styles/**/*.scss]` it will update each time you save any file and still only output main.scss as main.css.

Hope that helps.
