### ISSUE TITLE
map-stream is not defined in dependencies.

### ISSUE THREAD

**Issue by jmsalazar84** [Sonaryr/eleventy-plugin-sass#17]
the **map-stream** dependency is not registered in the package.json file.

> eleventy --serve
Eleventy fatal error: (more in DEBUG output)
> Error in your Eleventy config file '/home/jmsalazar/jms/pp/.eleventy.js'. You may need to run `npm install`.
`EleventyConfigError` was thrown
> Cannot find module 'map-stream'

**Comment by Sonaryr** [comment]
Added as a dependency
